---
- name: Fail if required Paperless AI settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - paperless_ai_uid
    - paperless_ai_gid
    - paperless_ai_hostname
    - paperless_ai_path_prefix
    - paperless_ai_container_network
    - paperless_ai_paperless_api_token
    
- name: Run if Traefik is enabled
  when: paperless_ai_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Paperless AI are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - paperless_ai_container_labels_traefik_hostname
        - paperless_ai_container_labels_traefik_path_prefix

    - name: Fail if paperless_ai_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          paperless_ai_container_labels_traefik_path_prefix (`{{ paperless_ai_container_labels_traefik_path_prefix }}`) must be `/`.
          Paperless AI does not support hosting under a subpath yet.
      when: "paperless_ai_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `paperless_ai_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if paperless_ai_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          paperless_ai_container_labels_traefik_path_prefix (`{{ paperless_ai_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/paperless_ai`).
      when: "paperless_ai_container_labels_traefik_path_prefix != '/' and paperless_ai_container_labels_traefik_path_prefix[-1] == '/'"
