---
galaxy_info:
  author: Suguru Hirahara
  company: progressiv
  role_name: pterodactyl_panel
  namespace: progressiv
  description: Pterodactyl Panel
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - all
  license: AGPL-3.0-or-later
  min_ansible_version: "2.1"
