---
# Project source code URL: https://github.com/clusterzx/paperless-ai

paperless_ai_enabled: true

paperless_ai_identifier: paperless-ai
paperless_ai_base_path: "{{ mash_playbook_base_path }}/{{ paperless_ai_identifier }}"

# `paperless_ai_data_path` is used for storing data in mounted directories
paperless_ai_data_path: "{{ paperless_ai_base_path }}/data"
paperless_ai_nltk_data_path: "{{ paperless_ai_base_path }}/nltk_data"
paperless_ai_cache_path: "{{ paperless_ai_base_path }}/.cache"
paperless_ai_pm2_path: "{{ paperless_ai_base_path }}/.pm2"
paperless_ai_logs_path: "{{ paperless_ai_base_path }}/logs"
paperless_ai_openai_path: "{{ paperless_ai_base_path }}/openai"
paperless_ai_public_images_path: "{{ paperless_ai_base_path }}/public"

# renovate: datasource=docker depName=clusterzx/paperless-ai versioning=semver
paperless_ai_version: 3.0.9

paperless_ai_uid: ""
paperless_ai_gid: ""

paperless_ai_scheme: https

# The hostname at which Paperless AI is served.
paperless_ai_hostname: ""

# The path at which Paperless AI is served.
# This value must either be `/` or not end with a slash (e.g. `/paperless-ai`).
#
# Hosting Paperless AI under a subpath does not seem to be possible due to Paperless AI's
# technical limitations.
paperless_ai_path_prefix: /

paperless_ai_paperless_url: ""
paperless_ai_paperless_api_token: ""

paperless_ai_container_image: "{{ paperless_ai_container_image_registry_prefix }}clusterzx/paperless-ai:{{ paperless_ai_container_image_tag }}"
paperless_ai_container_image_tag: "{{ paperless_ai_version }}"
paperless_ai_container_image_registry_prefix: "{{ paperless_ai_container_image_registry_prefix_upstream }}"
paperless_ai_container_image_registry_prefix_upstream: "{{ paperless_ai_container_image_registry_prefix_upstream_default }}"
paperless_ai_container_image_registry_prefix_upstream_default: docker.io/
paperless_ai_container_image_force_pull: "{{ paperless_ai_container_image.endswith(':latest') }}"

paperless_ai_container_image_self_build: false
paperless_ai_container_image_self_build_name: "clusterzx/paperless-ai:{{ paperless_ai_container_image_self_build_repo_version }}"
paperless_ai_container_image_self_build_repo: "https://github.com/clusterzx/paperless-ai.git"
paperless_ai_container_image_self_build_repo_version: "{{ paperless_ai_version if paperless_ai_version != 'latest' else 'main' }}"
paperless_ai_container_image_self_build_src_files_path: "{{ paperless_ai_base_path }}/docker-src"

# Controls whether the container exposes its HTTP port (tcp/80 in the container).
#
# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:2586"), or empty string to not expose.
paperless_ai_container_http_host_bind_port: ""

# The base container network. It will be auto-created by this role if it doesn't exist already.
paperless_ai_container_network: "{{ paperless_ai_identifier }}"

# The port number in the container
paperless_ai_container_http_port: 3000

# A list of additional container networks that the container would be connected to.
# The role does not create these networks, so make sure they already exist.
# Use this to expose this container to another reverse proxy, which runs in a different container network.
paperless_ai_container_additional_networks: "{{ paperless_ai_container_additional_networks_auto + paperless_ai_container_additional_networks_custom }}"
paperless_ai_container_additional_networks_auto: []
paperless_ai_container_additional_networks_custom: []

# A list of additional "volumes" to mount in the container.
# This list gets populated dynamically at runtime. You can provide a different default value,
# if you wish to mount your own files into the container.
# Contains definition objects like this: `{"type": "bind", "src": "/outside", "dst": "/inside", "options": "readonly"}.
# See the `--mount` documentation for the `docker run` command.
paperless_ai_container_additional_volumes: "{{ paperless_ai_container_additional_volumes_auto + paperless_ai_container_additional_volumes_custom }}"
paperless_ai_container_additional_volumes_auto: []
paperless_ai_container_additional_volumes_custom: []

# paperless_ai_container_labels_traefik_enabled controls whether labels to assist a Traefik reverse-proxy will be attached to the container.
# See `../templates/labels.j2` for details.
#
# To inject your own other container labels, see `paperless_ai_container_labels_additional_labels`.
paperless_ai_container_labels_traefik_enabled: true
paperless_ai_container_labels_traefik_docker_network: "{{ paperless_ai_container_network }}"
paperless_ai_container_labels_traefik_hostname: "{{ paperless_ai_hostname }}"
# The path prefix must either be `/` or not end with a slash (e.g. `/paperless-ai`).
paperless_ai_container_labels_traefik_path_prefix: "{{ paperless_ai_path_prefix }}"
paperless_ai_container_labels_traefik_rule: "Host(`{{ paperless_ai_container_labels_traefik_hostname }}`){% if paperless_ai_container_labels_traefik_path_prefix != '/' %} && PathPrefix(`{{ paperless_ai_container_labels_traefik_path_prefix }}`){% endif %}"
paperless_ai_container_labels_traefik_priority: 0
paperless_ai_container_labels_traefik_entrypoints: web-secure
paperless_ai_container_labels_traefik_tls: "{{ paperless_ai_container_labels_traefik_entrypoints != 'web' }}"
paperless_ai_container_labels_traefik_tls_certResolver: default  # noqa var-naming

# Controls which additional headers to attach to all HTTP requests.
# To add your own custom request headers, use `paperless_ai_container_labels_traefik_additional_request_headers_custom`
paperless_ai_container_labels_traefik_additional_request_headers: "{{ paperless_ai_container_labels_traefik_additional_request_headers_auto | combine(paperless_ai_container_labels_traefik_additional_request_headers_custom) }}"
paperless_ai_container_labels_traefik_additional_request_headers_auto: {}
paperless_ai_container_labels_traefik_additional_request_headers_custom: {}

# Controls which additional headers to attach to all HTTP responses.
# To add your own custom response headers, use `paperless_ai_container_labels_traefik_additional_response_headers_custom`
paperless_ai_container_labels_traefik_additional_response_headers: "{{ paperless_ai_container_labels_traefik_additional_response_headers_auto | combine(paperless_ai_container_labels_traefik_additional_response_headers_custom) }}"
paperless_ai_container_labels_traefik_additional_response_headers_auto: |
  {{
    {}
    | combine ({'X-XSS-Protection': paperless_ai_http_header_xss_protection} if paperless_ai_http_header_xss_protection else {})
    | combine ({'X-Content-Type-Options': paperless_ai_http_header_content_type_options} if paperless_ai_http_header_content_type_options else {})
    | combine ({'Content-Security-Policy': paperless_ai_http_header_content_security_policy} if paperless_ai_http_header_content_security_policy else {})
    | combine ({'Permissions-Policy': paperless_ai_http_header_permissions_policy} if paperless_ai_http_header_permissions_policy else {})
    | combine ({'Strict-Transport-Security': paperless_ai_http_header_strict_transport_security} if paperless_ai_http_header_strict_transport_security and paperless_ai_container_labels_traefik_tls else {})
  }}
paperless_ai_container_labels_traefik_additional_response_headers_custom: {}

# paperless_ai_container_labels_additional_labels contains a multiline string with additional labels to add to the container label file.
# See `../templates/labels.j2` for details.
# To add your own custom labels, use `paperless_ai_container_labels_additional_labels_custom`
#
# Example:
# paperless_ai_container_labels_additional_labels_custom:
#   - my.label=1
#   - another.label="here"
paperless_ai_container_labels_additional_labels: "{{ paperless_ai_container_labels_additional_labels_auto + paperless_ai_container_labels_additional_labels_custom }}"
paperless_ai_container_labels_additional_labels_auto: []
paperless_ai_container_labels_additional_labels_custom: []

# A list of extra arguments to pass to the container (`docker create` command)
paperless_ai_container_extra_arguments: "{{ paperless_ai_container_extra_arguments_auto + paperless_ai_container_extra_arguments_custom }}"
paperless_ai_container_extra_arguments_auto: []
paperless_ai_container_extra_arguments_custom: []

# Specifies the value of the `X-XSS-Protection` header
# Stops pages from loading when they detect reflected cross-site scripting (XSS) attacks.
#
# Learn more about it is here:
# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
# - https://portswigger.net/web-security/cross-site-scripting/reflected
paperless_ai_http_header_xss_protection: "1; mode=block"

# Specifies the value of the `X-Content-Type-Options` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
paperless_ai_http_header_content_type_options: nosniff

# Specifies the value of the `Content-Security-Policy` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
paperless_ai_http_header_content_security_policy: frame-ancestors 'self'

# Specifies the value of the `Permissions-Policy` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy
paperless_ai_http_header_permissions_policy: "{{ 'interest-cohort=()' if paperless_ai_floc_optout_enabled else '' }}"

# Specifies the value of the `Strict-Transport-Security` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
paperless_ai_http_header_strict_transport_security: "max-age=31536000; includeSubDomains{{ '; preload' if paperless_ai_hsts_preload_enabled else '' }}"

# Controls whether to send a "Permissions-Policy interest-cohort=();" header along with all responses
#
# Learn more about what it is here:
# - https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea
# - https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
# - https://amifloced.org/
#
# Of course, a better solution is to just stop using browsers (like Chrome), which participate in such tracking practices.
# See: `paperless_ai_http_header_permissions_policy`
paperless_ai_floc_optout_enabled: true

# Controls if HSTS preloading is enabled
#
# In its strongest and recommended form, the [HSTS policy](https://www.chromium.org/hsts) includes all subdomains, and
# indicates a willingness to be "preloaded" into browsers:
# `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`
# For more information visit:
# - https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
# - https://hstspreload.org/#opt-in
# See: `paperless_ai_http_header_strict_transport_security`
paperless_ai_hsts_preload_enabled: false

# List of systemd services that the Paperless AI systemd service depends on
paperless_ai_systemd_required_services_list: "{{ paperless_ai_systemd_required_services_list_default + paperless_ai_systemd_required_services_list_auto + paperless_ai_systemd_required_services_list_custom }}"
paperless_ai_systemd_required_services_list_default: "{{ [devture_systemd_docker_base_docker_service_name] if devture_systemd_docker_base_docker_service_name else [] }}"
paperless_ai_systemd_required_services_list_auto: []
paperless_ai_systemd_required_services_list_custom: []

# List of systemd services that the Paperless AI systemd service wants
paperless_ai_systemd_wanted_services_list: "{{ paperless_ai_systemd_wanted_services_list_default + paperless_ai_systemd_wanted_services_list_auto + paperless_ai_systemd_wanted_services_list_custom }}"
paperless_ai_systemd_wanted_services_list_default: []
paperless_ai_systemd_wanted_services_list_auto: []
paperless_ai_systemd_wanted_services_list_custom: []

paperless_ai_environment_variables_tz: UTC

# Additional environment variables.
paperless_ai_environment_variables_additional_variables: ""
