# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2025 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Pterodactyl Panel settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - pterodactyl_panel_uid
    - pterodactyl_panel_gid
    - pterodactyl_panel_path_prefix
    - pterodactyl_panel_container_network

- name: Run if Traefik is enabled
  when: pterodactyl_panel_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Pterodactyl Panel are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - pterodactyl_panel_container_labels_traefik_hostname
        - pterodactyl_panel_container_labels_traefik_path_prefix

    - name: Fail if pterodactyl_panel_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          pterodactyl_panel_container_labels_traefik_path_prefix (`{{ pterodactyl_panel_container_labels_traefik_path_prefix }}`) must be `/`.
          Pterodactyl Panel does not support hosting under a subpath yet.
      when: "pterodactyl_panel_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `pterodactyl_panel_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if pterodactyl_panel_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          pterodactyl_panel_container_labels_traefik_path_prefix (`{{ pterodactyl_panel_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/pterodactyl_panel`).
      when: "pterodactyl_panel_container_labels_traefik_path_prefix != '/' and pterodactyl_panel_container_labels_traefik_path_prefix[-1] == '/'"
