# SPDX-FileCopyrightText: 2023 - 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Geb√ºhr
# SPDX-FileCopyrightText: 2024 Sergio Durigan Junior
# SPDX-FileCopyrightText: 2025 MASH project contributors
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2025 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

pterodactyl_panel_enabled: true

pterodactyl_panel_identifier: pterodactyl-panel
pterodactyl_panel_base_path: "/{{ pterodactyl_panel_identifier }}"

# renovate: datasource=docker depName=ghcr.io/<ROLE_REPO>
pterodactyl_panel_version: 0.25.0

pterodactyl_panel_uid: ""
pterodactyl_panel_gid: ""

pterodactyl_panel_scheme: https

# The hostname at which Pterodactyl Panel is served.
pterodactyl_panel_hostname: ""

# The path at which Pterodactyl Panel is exposed.
# This value must either be `/` or not end with a slash (e.g. `/pterodactyl-panel`).
#
# Hosting Pterodactyl Panel under a subpath does not seem to be possible due to Pterodactyl Panel's
# technical limitations.
pterodactyl_panel_path_prefix: /

pterodactyl_panel_container_image: "{{ pterodactyl_panel_container_image_registry_prefix }}pterodactyl/panel:{{ pterodactyl_panel_container_image_tag }}"
pterodactyl_panel_container_image_tag: "{{ pterodactyl_panel_version }}"
pterodactyl_panel_container_image_registry_prefix: "{{ pterodactyl_panel_container_image_registry_prefix_upstream }}"
pterodactyl_panel_container_image_registry_prefix_upstream: "{{ pterodactyl_panel_container_image_registry_prefix_upstream_default }}"
pterodactyl_panel_container_image_registry_prefix_upstream_default: ghcr.io/
pterodactyl_panel_container_image_force_pull: "{{ pterodactyl_panel_container_image.endswith(':latest') }}"

# Controls whether the container exposes its HTTP port (tcp/3000 in the container).
#
# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:3000"), or empty string to not expose.
pterodactyl_panel_container_http_host_bind_port: ""

# The base container network. It will be auto-created by this role if it doesn't exist already.
pterodactyl_panel_container_network: "{{ pterodactyl_panel_identifier }}"

# The port number in the container
pterodactyl_panel_container_http_port: 3000

# A list of additional container networks that the container would be connected to.
# The role does not create these networks, so make sure they already exist.
# Use this to expose this container to another reverse proxy, which runs in a different container network.
pterodactyl_panel_container_additional_networks: "{{ pterodactyl_panel_container_additional_networks_auto + pterodactyl_panel_container_additional_networks_custom }}"
pterodactyl_panel_container_additional_networks_auto: []
pterodactyl_panel_container_additional_networks_custom: []

# A list of additional "volumes" to mount in the container.
# This list gets populated dynamically at runtime. You can provide a different default value,
# if you wish to mount your own files into the container.
# Contains definition objects like this: `{"type": "bind", "src": "/outside", "dst": "/inside", "options": "readonly"}.
# See the `--mount` documentation for the `docker run` command.
pterodactyl_panel_container_additional_volumes: "{{ pterodactyl_panel_container_additional_volumes_auto + pterodactyl_panel_container_additional_volumes_custom }}"
pterodactyl_panel_container_additional_volumes_auto: []
pterodactyl_panel_container_additional_volumes_custom: []

# pterodactyl_panel_container_labels_traefik_enabled controls whether labels to assist a Traefik reverse-proxy will be attached to the container.
# See `../templates/labels.j2` for details.
#
# To inject your own other container labels, see `pterodactyl_panel_container_labels_additional_labels`.
pterodactyl_panel_container_labels_traefik_enabled: false
pterodactyl_panel_container_labels_traefik_docker_network: "{{ pterodactyl_panel_container_network }}"
pterodactyl_panel_container_labels_traefik_hostname: "{{ pterodactyl_panel_hostname }}"
# The path prefix must either be `/` or not end with a slash (e.g. `/pterodactyl_panel`).
pterodactyl_panel_container_labels_traefik_path_prefix: "{{ pterodactyl_panel_path_prefix }}"
pterodactyl_panel_container_labels_traefik_rule: "Host(`{{ pterodactyl_panel_container_labels_traefik_hostname }}`){% if pterodactyl_panel_container_labels_traefik_path_prefix != '/' %} && PathPrefix(`{{ pterodactyl_panel_container_labels_traefik_path_prefix }}`){% endif %}"
pterodactyl_panel_container_labels_traefik_priority: 0
pterodactyl_panel_container_labels_traefik_entrypoints: web-secure
pterodactyl_panel_container_labels_traefik_tls: "{{ pterodactyl_panel_container_labels_traefik_entrypoints != 'web' }}"
pterodactyl_panel_container_labels_traefik_tls_certResolver: default  # noqa var-naming

# Controls which additional headers to attach to all HTTP requests.
# To add your own custom request headers, use `pterodactyl_panel_container_labels_traefik_additional_request_headers_custom`
pterodactyl_panel_container_labels_traefik_additional_request_headers: "{{ pterodactyl_panel_container_labels_traefik_additional_request_headers_auto | combine(pterodactyl_panel_container_labels_traefik_additional_request_headers_custom) }}"
pterodactyl_panel_container_labels_traefik_additional_request_headers_auto: {}
pterodactyl_panel_container_labels_traefik_additional_request_headers_custom: {}

# Controls which additional headers to attach to all HTTP responses.
# To add your own custom response headers, use `pterodactyl_panel_container_labels_traefik_additional_response_headers_custom`
pterodactyl_panel_container_labels_traefik_additional_response_headers: "{{ pterodactyl_panel_container_labels_traefik_additional_response_headers_auto | combine(pterodactyl_panel_container_labels_traefik_additional_response_headers_custom) }}"
pterodactyl_panel_container_labels_traefik_additional_response_headers_auto: |
  {{
    {}
    | combine ({'X-XSS-Protection': pterodactyl_panel_http_header_xss_protection} if pterodactyl_panel_http_header_xss_protection else {})
    | combine ({'X-Content-Type-Options': pterodactyl_panel_http_header_content_type_options} if pterodactyl_panel_http_header_content_type_options else {})
    | combine ({'Content-Security-Policy': pterodactyl_panel_http_header_content_security_policy} if pterodactyl_panel_http_header_content_security_policy else {})
    | combine ({'Permissions-Policy': pterodactyl_panel_http_header_permissions_policy} if pterodactyl_panel_http_header_permissions_policy else {})
    | combine ({'Strict-Transport-Security': pterodactyl_panel_http_header_strict_transport_security} if pterodactyl_panel_http_header_strict_transport_security and pterodactyl_panel_container_labels_traefik_tls else {})
  }}
pterodactyl_panel_container_labels_traefik_additional_response_headers_custom: {}

# pterodactyl_panel_container_labels_additional_labels contains a multiline string with additional labels to add to the container label file.
# See `../templates/labels.j2` for details.
#
# Example:
# pterodactyl_panel_container_labels_additional_labels: |
#   my.label=1
#   another.label="here"
pterodactyl_panel_container_labels_additional_labels: ""

# A list of extra arguments to pass to the container (`docker run` command)
pterodactyl_panel_container_extra_arguments: []

# Specifies the value of the `X-XSS-Protection` header
# Stops pages from loading when they detect reflected cross-site scripting (XSS) attacks.
#
# Learn more about it is here:
# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
# - https://portswigger.net/web-security/cross-site-scripting/reflected
pterodactyl_panel_http_header_xss_protection: "1; mode=block"

# Specifies the value of the `X-Content-Type-Options` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
pterodactyl_panel_http_header_content_type_options: nosniff

# Specifies the value of the `Content-Security-Policy` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
pterodactyl_panel_http_header_content_security_policy: frame-ancestors 'self'

# Specifies the value of the `Permissions-Policy` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy
pterodactyl_panel_http_header_permissions_policy: "{{ 'interest-cohort=()' if pterodactyl_panel_floc_optout_enabled else '' }}"

# Specifies the value of the `Strict-Transport-Security` header.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
pterodactyl_panel_http_header_strict_transport_security: "max-age=31536000; includeSubDomains{{ '; preload' if pterodactyl_panel_hsts_preload_enabled else '' }}"

# Controls whether to send a "Permissions-Policy interest-cohort=();" header along with all responses
#
# Learn more about what it is here:
# - https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea
# - https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
# - https://amifloced.org/
#
# Of course, a better solution is to just stop using browsers (like Chrome), which participate in such tracking practices.
# See: `pterodactyl_panel_http_header_permissions_policy`
pterodactyl_panel_floc_optout_enabled: true

# Controls if HSTS preloading is enabled
#
# In its strongest and recommended form, the [HSTS policy](https://www.chromium.org/hsts) includes all subdomains, and
# indicates a willingness to be "preloaded" into browsers:
# `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`
# For more information visit:
# - https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
# - https://hstspreload.org/#opt-in
# See: `pterodactyl_panel_http_header_strict_transport_security`
pterodactyl_panel_hsts_preload_enabled: false

# List of systemd services that the Pterodactyl Panel systemd service depends on
pterodactyl_panel_systemd_required_services_list: "{{ pterodactyl_panel_systemd_required_services_list_default + pterodactyl_panel_systemd_required_services_list_auto + pterodactyl_panel_systemd_required_services_list_custom }}"
pterodactyl_panel_systemd_required_services_list_default: "{{ [devture_systemd_docker_base_docker_service_name] if devture_systemd_docker_base_docker_service_name else [] }}"
pterodactyl_panel_systemd_required_services_list_auto: []
pterodactyl_panel_systemd_required_services_list_custom: []

# List of systemd services that the Pterodactyl Panel systemd service wants
pterodactyl_panel_systemd_wanted_services_list: "{{ pterodactyl_panel_systemd_wanted_services_list_default + pterodactyl_panel_systemd_wanted_services_list_auto + pterodactyl_panel_systemd_wanted_services_list_custom }}"
pterodactyl_panel_systemd_wanted_services_list_default: []
pterodactyl_panel_systemd_wanted_services_list_auto: []
pterodactyl_panel_systemd_wanted_services_list_custom: []
